/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthTransfersRouteImport } from './routes/_auth/transfers'
import { Route as AuthScheduledRouteImport } from './routes/_auth/scheduled'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthIndexRouteImport } from './routes/_auth/_index'
import { Route as AuthPaymentsIndexRouteImport } from './routes/_auth/payments/index'
import { Route as AuthTransfersTransferIdRouteImport } from './routes/_auth/transfers.$transferId'
import { Route as AuthPaymentsTransfersRouteImport } from './routes/_auth/payments/transfers'
import { Route as AuthPaymentsScheduledRouteImport } from './routes/_auth/payments/scheduled'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthTransfersRoute = AuthTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthScheduledRoute = AuthScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaymentsIndexRoute = AuthPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTransfersTransferIdRoute = AuthTransfersTransferIdRouteImport.update({
  id: '/$transferId',
  path: '/$transferId',
  getParentRoute: () => AuthTransfersRoute,
} as any)
const AuthPaymentsTransfersRoute = AuthPaymentsTransfersRouteImport.update({
  id: '/payments/transfers',
  path: '/payments/transfers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaymentsScheduledRoute = AuthPaymentsScheduledRouteImport.update({
  id: '/payments/scheduled',
  path: '/payments/scheduled',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/profile': typeof AuthProfileRoute
  '/scheduled': typeof AuthScheduledRoute
  '/transfers': typeof AuthTransfersRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/payments/scheduled': typeof AuthPaymentsScheduledRoute
  '/payments/transfers': typeof AuthPaymentsTransfersRoute
  '/transfers/$transferId': typeof AuthTransfersTransferIdRoute
  '/payments/': typeof AuthPaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/profile': typeof AuthProfileRoute
  '/scheduled': typeof AuthScheduledRoute
  '/transfers': typeof AuthTransfersRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/payments/scheduled': typeof AuthPaymentsScheduledRoute
  '/payments/transfers': typeof AuthPaymentsTransfersRoute
  '/transfers/$transferId': typeof AuthTransfersTransferIdRoute
  '/payments': typeof AuthPaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/_index': typeof AuthIndexRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/scheduled': typeof AuthScheduledRoute
  '/_auth/transfers': typeof AuthTransfersRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_auth/payments/scheduled': typeof AuthPaymentsScheduledRoute
  '/_auth/payments/transfers': typeof AuthPaymentsTransfersRoute
  '/_auth/transfers/$transferId': typeof AuthTransfersTransferIdRoute
  '/_auth/payments/': typeof AuthPaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/scheduled'
    | '/transfers'
    | '/login'
    | '/register'
    | '/payments/scheduled'
    | '/payments/transfers'
    | '/transfers/$transferId'
    | '/payments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/scheduled'
    | '/transfers'
    | '/login'
    | '/register'
    | '/payments/scheduled'
    | '/payments/transfers'
    | '/transfers/$transferId'
    | '/payments'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/_index'
    | '/_auth/profile'
    | '/_auth/scheduled'
    | '/_auth/transfers'
    | '/_public/login'
    | '/_public/register'
    | '/_auth/payments/scheduled'
    | '/_auth/payments/transfers'
    | '/_auth/transfers/$transferId'
    | '/_auth/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/transfers': {
      id: '/_auth/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthTransfersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scheduled': {
      id: '/_auth/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof AuthScheduledRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_index': {
      id: '/_auth/_index'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/payments/': {
      id: '/_auth/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthPaymentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transfers/$transferId': {
      id: '/_auth/transfers/$transferId'
      path: '/$transferId'
      fullPath: '/transfers/$transferId'
      preLoaderRoute: typeof AuthTransfersTransferIdRouteImport
      parentRoute: typeof AuthTransfersRoute
    }
    '/_auth/payments/transfers': {
      id: '/_auth/payments/transfers'
      path: '/payments/transfers'
      fullPath: '/payments/transfers'
      preLoaderRoute: typeof AuthPaymentsTransfersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/payments/scheduled': {
      id: '/_auth/payments/scheduled'
      path: '/payments/scheduled'
      fullPath: '/payments/scheduled'
      preLoaderRoute: typeof AuthPaymentsScheduledRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthTransfersRouteChildren {
  AuthTransfersTransferIdRoute: typeof AuthTransfersTransferIdRoute
}

const AuthTransfersRouteChildren: AuthTransfersRouteChildren = {
  AuthTransfersTransferIdRoute: AuthTransfersTransferIdRoute,
}

const AuthTransfersRouteWithChildren = AuthTransfersRoute._addFileChildren(
  AuthTransfersRouteChildren,
)

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthScheduledRoute: typeof AuthScheduledRoute
  AuthTransfersRoute: typeof AuthTransfersRouteWithChildren
  AuthPaymentsScheduledRoute: typeof AuthPaymentsScheduledRoute
  AuthPaymentsTransfersRoute: typeof AuthPaymentsTransfersRoute
  AuthPaymentsIndexRoute: typeof AuthPaymentsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthScheduledRoute: AuthScheduledRoute,
  AuthTransfersRoute: AuthTransfersRouteWithChildren,
  AuthPaymentsScheduledRoute: AuthPaymentsScheduledRoute,
  AuthPaymentsTransfersRoute: AuthPaymentsTransfersRoute,
  AuthPaymentsIndexRoute: AuthPaymentsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
